### ISSUE TITLE
Error in eval

### ISSUE THREAD

**Issue by Juancortes7** [luifrancgom/marketing_research_and_analytics#5]
Good morning professor

I was to trying to follow the instructions about chapter 4 that to start recording april 24 and then continuos recording 26 but when I  click in source appers the next error:
![image](https://github.com/luifrancgom/marketing_research_and_analytics/assets/167640974/368bfc78-769e-4596-a02a-a6392a013080)

Actually I tried to fix it type ? and the error because I need to information for fix it but it's not possible because appears the same.

So it's the reason I need to help for continuo the review last recording please.

 - Operating system: Windows 10
 - R version: 4.3.3
 - Quarto version: 1.4.553

Thank you so much

**Comment by luifrancgom** [comment]
Please don't share code as an image only. If you do that I can not help you. When reporting an issue the template says that you need to specify a **Minimal Reproducible Example (MRE)**. I need to know what you are trying to run. 

Please follow the instructions of the template. Check [this](https://stackoverflow.com/help/minimal-reproducible-example) and [this](https://reprex.tidyverse.org/)

**Comment by luifrancgom** [comment]
A **Minimal Reproducible Example (MRE)** was not attach. Closing issue.
